//! Bounded machine-evidence receipts emitted by trusted verifier tools.
//!
//! A receipt is not authoritative evidence. It intentionally carries no Task,
//! Run, invocation, origin, or bundle identity: `zk-engine` supplies those only
//! after the physical verifier invocation has reached durable `succeeded`.

use serde::{Deserialize, Serialize};
use serde_json::Value;

use crate::ToolOutput;

/// Current machine-evidence receipt contract.
pub const EVIDENCE_RECEIPT_SCHEMA_VERSION: u16 = 1;
/// Maximum verifier steps accepted from one physical invocation.
pub const MAX_EVIDENCE_RECEIPT_ITEMS: usize = 50;
const MAX_EVIDENCE_KIND_BYTES: usize = 128;
const MAX_EVIDENCE_CLAIM_BYTES: usize = 4_096;
const MAX_EVIDENCE_SUMMARY_BYTES: usize = 8_192;
const MAX_EVIDENCE_ITEM_META_BYTES: usize = 32 * 1_024;
const MAX_EVIDENCE_RECEIPT_META_BYTES: usize = 256 * 1_024;

/// Closed verdict vocabulary for deterministic verifier output.
#[derive(Clone, Copy, Debug, Deserialize, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase")]
pub enum EvidenceReceiptVerdict {
    /// Every required check passed.
    Verified,
    /// At least one deterministic check failed.
    Failed,
    /// Checks completed but did not establish a conclusion.
    Inconclusive,
    /// The requested verification was not available.
    Unavailable,
}

impl EvidenceReceiptVerdict {
    /// Database representation used by the evidence ledger.
    #[must_use]
    pub const fn as_db(self) -> &'static str {
        match self {
            Self::Verified => "verified",
            Self::Failed => "failed",
            Self::Inconclusive => "inconclusive",
            Self::Unavailable => "unavailable",
        }
    }
}

/// One bounded observation made by the verifier invocation.
#[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct EvidenceReceiptItem {
    /// Stable item category, for example `browser_journey_step`.
    #[serde(rename = "type")]
    pub item_type: String,
    /// Redacted, bounded display summary.
    pub summary: Option<String>,
    /// Optional content-addressed blob produced by the trusted tool bridge.
    pub blob_sha256: Option<String>,
    /// Bounded structured observation. Ownership fields are forbidden here.
    pub meta: Option<Value>,
    /// Deterministic zero-based order.
    pub sort_order: u32,
}

/// Non-authoritative output receipt consumed by `zk-engine` after success.
#[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct EvidenceReceipt {
    /// Receipt schema version.
    pub schema_version: u16,
    /// Evidence category.
    pub kind: String,
    /// Redacted acceptance claim.
    pub claim: Option<String>,
    /// Deterministic verdict reported by the verifier.
    pub verdict: EvidenceReceiptVerdict,
    /// RFC 3339 observation time generated by the trusted bridge.
    pub observed_at: String,
    /// Ordered observations.
    pub items: Vec<EvidenceReceiptItem>,
}

impl EvidenceReceipt {
    /// Validate all bounds and reject caller-controlled ownership metadata.
    #[must_use]
    pub fn is_valid(&self) -> bool {
        if self.schema_version != EVIDENCE_RECEIPT_SCHEMA_VERSION
            || self.kind.is_empty()
            || self.kind.len() > MAX_EVIDENCE_KIND_BYTES
            || self.observed_at.is_empty()
            || self.observed_at.len() > 64
            || chrono::DateTime::parse_from_rfc3339(&self.observed_at).is_err()
            || self.items.is_empty()
            || self.items.len() > MAX_EVIDENCE_RECEIPT_ITEMS
            || self
                .claim
                .as_ref()
                .is_some_and(|claim| claim.len() > MAX_EVIDENCE_CLAIM_BYTES)
        {
            return false;
        }

        let mut total_meta_bytes = 0_usize;
        self.items.iter().enumerate().all(|(index, item)| {
            let meta_bytes = item
                .meta
                .as_ref()
                .and_then(|meta| serde_json::to_vec(meta).ok())
                .map_or(0, |encoded| encoded.len());
            total_meta_bytes = total_meta_bytes.saturating_add(meta_bytes);
            !item.item_type.is_empty()
                && item.item_type.len() <= MAX_EVIDENCE_KIND_BYTES
                && item
                    .summary
                    .as_ref()
                    .is_none_or(|summary| summary.len() <= MAX_EVIDENCE_SUMMARY_BYTES)
                && item.blob_sha256.as_ref().is_none_or(|digest| {
                    digest.len() == 64 && digest.bytes().all(|byte| byte.is_ascii_hexdigit())
                })
                && item.sort_order == u32::try_from(index).unwrap_or(u32::MAX)
                && meta_bytes <= MAX_EVIDENCE_ITEM_META_BYTES
                && total_meta_bytes <= MAX_EVIDENCE_RECEIPT_META_BYTES
                && !item.meta.as_ref().is_some_and(contains_ownership_field)
        })
    }
}

fn contains_ownership_field(value: &Value) -> bool {
    match value {
        Value::Object(object) => object.iter().any(|(key, value)| {
            matches!(
                key.as_str(),
                "producerInvocationId"
                    | "producer_invocation_id"
                    | "taskId"
                    | "task_id"
                    | "runId"
                    | "run_id"
                    | "sessionId"
                    | "session_id"
            ) || contains_ownership_field(value)
        }),
        Value::Array(values) => values.iter().any(contains_ownership_field),
        _ => false,
    }
}

impl ToolOutput {
    /// Decode a valid verifier receipt from structured result metadata.
    #[must_use]
    pub fn evidence_receipt(&self) -> Option<EvidenceReceipt> {
        let value = self
            .metadata
            .as_ref()?
            .get("structuredResult")?
            .get("evidence")?
            .clone();
        let receipt: EvidenceReceipt = serde_json::from_value(value).ok()?;
        receipt.is_valid().then_some(receipt)
    }
}

#[cfg(test)]
mod tests {
    use serde_json::json;

    use super::*;

    fn valid_receipt() -> EvidenceReceipt {
        EvidenceReceipt {
            schema_version: EVIDENCE_RECEIPT_SCHEMA_VERSION,
            kind: "browser_journey".into(),
            claim: Some("page works".into()),
            verdict: EvidenceReceiptVerdict::Verified,
            observed_at: "2026-09-09T00:00:00.000000Z".into(),
            items: vec![EvidenceReceiptItem {
                item_type: "browser_journey_step".into(),
                summary: Some("navigate: passed".into()),
                blob_sha256: Some("a".repeat(64)),
                meta: Some(json!({"action":"navigate","ok":true})),
                sort_order: 0,
            }],
        }
    }

    #[test]
    fn accepts_only_bounded_ordered_receipts_without_ownership_claims() {
        assert!(valid_receipt().is_valid());

        let mut forged = valid_receipt();
        forged.items[0].meta = Some(json!({"nested":{"producerInvocationId":"forged"}}));
        assert!(!forged.is_valid());

        let mut unordered = valid_receipt();
        unordered.items[0].sort_order = 1;
        assert!(!unordered.is_valid());
    }

    #[test]
    fn tool_output_decodes_only_the_versioned_receipt() {
        let receipt = valid_receipt();
        let output = ToolOutput {
            content: "done".into(),
            is_error: false,
            metadata: Some(json!({
                "structuredResult": {"evidence": receipt}
            })),
        };
        assert_eq!(output.evidence_receipt(), Some(valid_receipt()));
    }
}
