//! Stable, bounded research receipts emitted by the built-in web tools.
//!
//! The receipt is execution metadata only. It deliberately contains a short
//! excerpt instead of the fetched page body; `zk-db` remains the sole research
//! ledger and revalidates every limit and producer identity before persistence.

use serde::{Deserialize, Serialize};

use crate::tool::ToolOutput;

/// Version of the metadata contract consumed by `zk-engine`.
pub const RESEARCH_RECEIPT_SCHEMA_VERSION: u16 = 1;
/// Maximum UTF-8 bytes accepted for a source URL.
pub const MAX_RESEARCH_URL_BYTES: usize = 4_096;
/// Maximum UTF-8 bytes accepted for a source title.
pub const MAX_RESEARCH_TITLE_BYTES: usize = 4_096;
/// Maximum UTF-8 bytes accepted for a provider name.
pub const MAX_RESEARCH_PROVIDER_BYTES: usize = 512;
/// Maximum UTF-8 bytes persisted for one search snippet or fetch excerpt.
pub const MAX_RESEARCH_EXCERPT_BYTES: usize = 8_192;
/// Maximum UTF-8 bytes accepted for the originating search query.
pub const MAX_RESEARCH_QUERY_BYTES: usize = 4_096;
/// A receipt cannot expand beyond the public `WebSearch` result cap.
pub const MAX_RESEARCH_RECEIPT_ENTRIES: usize = 10;

/// Physical web operation which produced a research receipt.
#[derive(Clone, Copy, Debug, Deserialize, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase")]
pub enum ResearchReceiptKind {
    /// A bounded search result page.
    WebSearch,
    /// One fetched public page.
    WebFetch,
}

/// One source and its bounded, attributable excerpt.
#[derive(Clone, Debug, Deserialize, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ResearchReceiptEntry {
    /// Canonical public URL.
    pub url: String,
    /// Page/result title, when known.
    pub title: Option<String>,
    /// Search provider/server identity, without credentials.
    pub provider: Option<String>,
    /// Short snippet or extract; never a complete fetched page.
    pub excerpt: Option<String>,
    /// One-based search rank. A fetch has no rank.
    pub rank: Option<u32>,
    /// HTTP response status for a fetch.
    pub http_status: Option<u16>,
    /// Normalized response content type for a fetch.
    pub content_type: Option<String>,
    /// Whether the source body/model-facing rendering was truncated.
    pub truncated: bool,
}

/// Versioned result metadata consumed after the invocation succeeds durably.
#[derive(Clone, Debug, Deserialize, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ResearchReceipt {
    /// Contract version.
    pub schema_version: u16,
    /// Tool family which produced the entries.
    pub kind: ResearchReceiptKind,
    /// Search query for `webSearch`; absent for `webFetch`.
    pub query: Option<String>,
    /// RFC 3339 observation time generated by the tool.
    pub fetched_at: String,
    /// Bounded sources in deterministic display order.
    pub entries: Vec<ResearchReceiptEntry>,
}

impl ResearchReceipt {
    /// Reject malformed or unexpectedly large metadata before it crosses into
    /// the engine. The database repeats these checks at the trust boundary.
    #[must_use]
    pub fn is_valid(&self) -> bool {
        if self.schema_version != RESEARCH_RECEIPT_SCHEMA_VERSION
            || self.fetched_at.is_empty()
            || self.fetched_at.len() > 64
            || self.entries.len() > MAX_RESEARCH_RECEIPT_ENTRIES
            || self
                .query
                .as_ref()
                .is_some_and(|value| value.len() > MAX_RESEARCH_QUERY_BYTES)
        {
            return false;
        }
        if matches!(self.kind, ResearchReceiptKind::WebSearch) && self.query.is_none() {
            return false;
        }
        if matches!(self.kind, ResearchReceiptKind::WebFetch)
            && (self.query.is_some() || self.entries.len() != 1)
        {
            return false;
        }
        self.entries.iter().enumerate().all(|(index, entry)| {
            !entry.url.is_empty()
                && entry.url.len() <= MAX_RESEARCH_URL_BYTES
                && entry
                    .title
                    .as_ref()
                    .is_none_or(|value| value.len() <= MAX_RESEARCH_TITLE_BYTES)
                && entry
                    .provider
                    .as_ref()
                    .is_none_or(|value| value.len() <= MAX_RESEARCH_PROVIDER_BYTES)
                && entry
                    .excerpt
                    .as_ref()
                    .is_none_or(|value| value.len() <= MAX_RESEARCH_EXCERPT_BYTES)
                && match self.kind {
                    ResearchReceiptKind::WebSearch => {
                        entry.rank == u32::try_from(index + 1).ok()
                            && entry.http_status.is_none()
                            && entry.content_type.is_none()
                    }
                    ResearchReceiptKind::WebFetch => entry.rank.is_none(),
                }
        })
    }
}

impl ToolOutput {
    /// Decode the standardized research receipt from structured tool metadata.
    #[must_use]
    pub fn research_receipt(&self) -> Option<ResearchReceipt> {
        let value = self
            .metadata
            .as_ref()?
            .get("structuredResult")?
            .get("research")?
            .clone();
        let receipt: ResearchReceipt = serde_json::from_value(value).ok()?;
        receipt.is_valid().then_some(receipt)
    }
}

/// Truncate to a UTF-8 byte ceiling without cutting a code point.
#[must_use]
pub fn truncate_utf8_bytes(value: &str, max_bytes: usize) -> String {
    if value.len() <= max_bytes {
        return value.to_owned();
    }
    let mut boundary = max_bytes;
    while boundary > 0 && !value.is_char_boundary(boundary) {
        boundary -= 1;
    }
    value[..boundary].to_owned()
}

#[cfg(test)]
mod tests {
    use serde_json::json;

    use super::*;

    #[test]
    fn decodes_only_bounded_versioned_receipts() {
        let output = ToolOutput {
            content: "visible".to_owned(),
            is_error: false,
            metadata: Some(json!({
                "structuredResult": {
                    "research": {
                        "schemaVersion": 1,
                        "kind": "webFetch",
                        "query": null,
                        "fetchedAt": "2026-09-09T00:00:00.000000Z",
                        "entries": [{
                            "url": "https://example.com/",
                            "title": "Example",
                            "provider": null,
                            "excerpt": "short",
                            "rank": null,
                            "httpStatus": 200,
                            "contentType": "text/html",
                            "truncated": false
                        }]
                    }
                }
            })),
        };
        assert_eq!(
            output.research_receipt().expect("receipt").kind,
            ResearchReceiptKind::WebFetch
        );

        let mut oversized = output;
        oversized.metadata.as_mut().expect("metadata")["structuredResult"]["research"]["entries"]
            [0]["excerpt"] = json!("x".repeat(MAX_RESEARCH_EXCERPT_BYTES + 1));
        assert!(oversized.research_receipt().is_none());
    }

    #[test]
    fn utf8_truncation_never_splits_a_character() {
        assert_eq!(truncate_utf8_bytes("a界b", 4), "a界");
    }
}
