//! Durable, fenced merge-summary units. Provider attempts use the ordinary LLM ledger.
#![allow(missing_docs, clippy::missing_errors_doc, clippy::too_many_arguments)]
use crate::{Db, DbError, session_merge_budget::MergeWriteBudget};
use rusqlite::{Connection, params};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

/// Source spans are UTF-8 byte offsets generated by the processor, never the model.
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct MergeInputRef {
    #[serde(rename = "ref")]
    pub reference: String,
    pub source_id: String,
    pub start: usize,
    pub end: usize,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct MergeUnitInput {
    pub inputs: Vec<MergeInputRef>,
    pub child_unit_ids: Vec<String>,
}

/// A completed unit is immutable; later epochs reuse its exact validated result.
#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct MergeSummaryUnit {
    pub unit_id: String,
    pub stage: String,
    pub ordinal: i64,
    pub input_json: String,
    pub input_hash: String,
    pub state: String,
    pub result_json: Option<String>,
    pub result_hash: Option<String>,
    pub model: String,
}

fn fence(conn: &Connection, id: &str, epoch: i64) -> Result<(), DbError> {
    let valid: bool = conn.query_row("SELECT EXISTS(SELECT 1 FROM session_merges WHERE id=?1 AND run_epoch=?2 AND status='preparing' AND snapshot_sealed=1)", params![id, epoch], |r| r.get(0))?;
    if valid {
        Ok(())
    } else {
        Err(DbError::Conflict("merge worker has been fenced".into()))
    }
}
fn insert_unit(
    conn: &Connection,
    id: &str,
    unit: &MergeSummaryUnit,
    disk: &mut MergeWriteBudget,
) -> Result<(), DbError> {
    disk.reserve(unit.input_json.len().saturating_add(1024))?;
    let inserted = conn.execute("INSERT OR IGNORE INTO session_merge_units(operation_id,unit_id,stage,ordinal,input_json,input_hash,state,model) VALUES(?1,?2,?3,?4,?5,?6,'pending',?7)",params![id,unit.unit_id,unit.stage,unit.ordinal,unit.input_json,unit.input_hash,unit.model])?;
    if inserted == 0 {
        let existing: (String,String) = conn.query_row("SELECT input_hash,input_json FROM session_merge_units WHERE operation_id=?1 AND unit_id=?2",params![id,unit.unit_id],|r|Ok((r.get(0)?,r.get(1)?)))?;
        if existing != (unit.input_hash.clone(), unit.input_json.clone()) {
            return Err(DbError::Conflict("merge unit input changed".into()));
        }
    }
    Ok(())
}
impl Db {
    /// A hidden, unprivileged accounting session survives source deletion.
    pub async fn create_merge_billing_session(
        &self,
        id: &str,
        epoch: i64,
        model: &str,
        workspace: &str,
    ) -> Result<(String, i64), DbError> {
        let (id, model, workspace) = (id.to_owned(), model.to_owned(), workspace.to_owned());
        self.with_writer(move|conn|{let tx=conn.transaction()?;fence(&tx,&id,epoch)?;
            let (request,created):(String,String)=tx.query_row("SELECT request_json,created_at FROM session_merges WHERE id=?1",[&id],|r|Ok((r.get(0)?,r.get(1)?)))?;
            let source=serde_json::from_str::<crate::SessionMergeRequest>(&request)?.primary_session_id;
            let session=uuid::Uuid::new_v4().to_string();
            let now=crate::time::format_rfc3339_micros(crate::time::now_millis());
            let metadata=serde_json::json!({"mergeOperationId":id,"mergeBilling":true,"referenceOnly":true,"sourceSessionId":source});
            tx.execute("INSERT INTO sessions(id,kind,model,working_dir,permission_mode,metadata_json,created_at,updated_at) VALUES(?1,'merge_billing',?2,?3,'DONT_ASK',?4,?5,?5)",params![session,model,workspace,metadata.to_string(),now])?;
            tx.commit()?;Ok((session,crate::time::parse_rfc3339_millis(&created).ok_or_else(||DbError::Invalid("invalid merge creation time".into()))?))
        }).await
    }
    /// Idempotently plan work against an immutable snapshot.
    pub async fn plan_merge_summary_unit(
        &self,
        id: &str,
        epoch: i64,
        unit: MergeSummaryUnit,
    ) -> Result<(), DbError> {
        let id = id.to_owned();
        self.with_writer(move |conn| {
            let tx = conn.transaction()?;
            fence(&tx, &id, epoch)?;
            insert_unit(&tx, &id, &unit, &mut MergeWriteBudget::new(&tx))?;
            tx.commit()?;
            Ok(())
        })
        .await
    }
    /// Load every planned unit in deterministic stage/ordinal order.
    pub async fn merge_summary_units(&self, id: &str) -> Result<Vec<MergeSummaryUnit>, DbError> {
        let id = id.to_owned();
        self.with_reader(move|conn| {
            let mut stmt=conn.prepare("SELECT unit_id,stage,ordinal,input_json,input_hash,state,result_json,result_hash,model FROM session_merge_units WHERE operation_id=?1 ORDER BY stage,ordinal,unit_id")?;
            Ok(stmt.query_map([id],|r|Ok(MergeSummaryUnit{unit_id:r.get(0)?,stage:r.get(1)?,ordinal:r.get(2)?,input_json:r.get(3)?,input_hash:r.get(4)?,state:r.get(5)?,result_json:r.get(6)?,result_hash:r.get(7)?,model:r.get(8)?}))?.collect::<Result<Vec<_>,_>>()?)
        }).await
    }
    /// Atomically replace a pending unit with two overlapping source spans.
    pub async fn split_merge_summary_unit(
        &self,
        id: &str,
        epoch: i64,
        parent: &str,
        left: MergeSummaryUnit,
        right: MergeSummaryUnit,
    ) -> Result<(), DbError> {
        let (id, parent) = (id.to_owned(), parent.to_owned());
        self.with_writer(move |conn| {
            let tx = conn.transaction()?;
            fence(&tx, &id, epoch)?;
            let state: String = tx.query_row(
                "SELECT state FROM session_merge_units WHERE operation_id=?1 AND unit_id=?2",
                params![id, parent],
                |r| r.get(0),
            )?;
            if state != "pending" {
                return Err(DbError::Conflict("only a pending unit can be split".into()));
            }
            let mut disk = MergeWriteBudget::new(&tx);
            insert_unit(&tx, &id, &left, &mut disk)?;
            insert_unit(&tx, &id, &right, &mut disk)?;
            tx.execute(
                "UPDATE session_merge_units SET state='split' WHERE operation_id=?1 AND unit_id=?2",
                params![id, parent],
            )?;
            tx.commit()?;
            Ok(())
        })
        .await
    }
    /// Publish a validated result exactly once under the current worker fence.
    pub async fn commit_merge_summary_unit(
        &self,
        id: &str,
        epoch: i64,
        unit: &str,
        result: String,
        hash: String,
        model: String,
    ) -> Result<(), DbError> {
        if format!("{:x}", Sha256::digest(result.as_bytes())) != hash {
            return Err(DbError::Validation("MERGE_RESULT_HASH_MISMATCH".into()));
        }
        let (id, unit) = (id.to_owned(), unit.to_owned());
        self.with_writer(move|conn|{
            let tx=conn.transaction()?;fence(&tx,&id,epoch)?;
            MergeWriteBudget::new(&tx).reserve(result.len().saturating_add(1024))?;
            if tx.execute("UPDATE session_merge_units SET state='completed',result_json=?1,result_hash=?2,model=?3 WHERE operation_id=?4 AND unit_id=?5 AND state='pending'",params![result,hash,model,id,unit])?!=1 {return Err(DbError::Conflict("unit already changed".into()));}
            tx.commit()?;Ok(())
        }).await
    }
    /// Update a truthful processing phase without mutating published operations.
    pub async fn set_merge_summary_stage(
        &self,
        id: &str,
        epoch: i64,
        stage: &str,
    ) -> Result<(), DbError> {
        let (id, stage) = (id.to_owned(), stage.to_owned());
        self.with_writer(move |conn| {
            fence(conn, &id, epoch)?;
            conn.execute(
                "UPDATE session_merges SET stage=?1 WHERE id=?2",
                params![stage, id],
            )?;
            Ok(())
        })
        .await
    }
    /// Bind a logical request to its task/run. Every physical retry is separately charged by `llm_calls`.
    pub async fn begin_merge_summary_attempt(
        &self,
        id: &str,
        epoch: i64,
        unit: &str,
        task: &str,
        run: &str,
    ) -> Result<String, DbError> {
        let (id, unit, task, run) = (
            id.to_owned(),
            unit.to_owned(),
            task.to_owned(),
            run.to_owned(),
        );
        self.with_writer(move|conn|{
            let tx=conn.transaction()?;fence(&tx,&id,epoch)?;
            let attempt=uuid::Uuid::new_v4().to_string();
            tx.execute("INSERT INTO session_merge_attempts(operation_id,attempt_id,unit_id,run_epoch,task_id,run_id,state,created_at) VALUES(?1,?2,?3,?4,?5,?6,'running',?7)",params![id,attempt,unit,epoch,task,run,crate::time::format_rfc3339_micros(crate::time::now_millis())])?;
            tx.commit()?;Ok(attempt)
        }).await
    }
    /// Attempt settlement is recorded even when cancellation has already fenced the worker.
    pub async fn finish_merge_summary_attempt(
        &self,
        attempt: &str,
        error: Option<String>,
    ) -> Result<(), DbError> {
        let attempt = attempt.to_owned();
        self.with_writer(move|conn|{conn.execute("UPDATE session_merge_attempts SET state=?1,error=?2 WHERE attempt_id=?3 AND state='running'",params![if error.is_some(){"failed"}else{"completed"},error,attempt])?;Ok(())}).await
    }
    /// Count all prior physical calls exactly once, regardless of retry/epoch boundaries.
    pub async fn merge_summary_usage(
        &self,
        id: &str,
        except_run: Option<String>,
    ) -> Result<(i64, i64, bool), DbError> {
        let id = id.to_owned();
        self.with_reader(move|conn|{
            Ok(conn.query_row("SELECT COALESCE(SUM(input_tokens+output_tokens+cache_read_tokens+cache_create_tokens),0),COALESCE(SUM(cost_nanos_usd),0),COALESCE(MIN(usage_complete),1) FROM llm_calls WHERE run_id IN (SELECT DISTINCT run_id FROM session_merge_attempts WHERE operation_id=?1) AND (?2 IS NULL OR run_id<>?2)",params![id,except_run],|r|Ok((r.get(0)?,r.get(1)?,r.get(2)?)))?)
        }).await
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    fn planned(id: &str) -> MergeSummaryUnit {
        MergeSummaryUnit {
            unit_id: id.into(),
            stage: "extracting".into(),
            ordinal: 0,
            input_json: format!("{{\"unit\":\"{id}\"}}"),
            input_hash: id.into(),
            state: "pending".into(),
            result_json: None,
            result_hash: None,
            model: "model".into(),
        }
    }
    #[tokio::test]
    #[allow(
        clippy::too_many_lines,
        reason = "One persisted summary fixture checks splitting, epoch fencing and immutable completed units across recovery"
    )]
    async fn split_plans_are_atomic_and_stale_epochs_cannot_commit_or_rewrite_completed_units() {
        let db = Db::open_in_memory().unwrap();
        let a = db.create_session("model", "/a").await.unwrap();
        let b = db.create_session("model", "/b").await.unwrap();
        let op = db
            .start_session_merge(
                "fencing".into(),
                crate::SessionMergeRequest {
                    source_session_ids: vec![a.id.clone(), b.id],
                    primary_session_id: a.id,
                    title: None,
                    model: None,
                },
            )
            .await
            .unwrap();
        db.plan_merge_summary_unit(&op.operation_id, op.run_epoch, planned("e0"))
            .await
            .unwrap();
        db.plan_merge_summary_unit(&op.operation_id, op.run_epoch, planned("e0"))
            .await
            .unwrap();
        let mut changed = planned("e0");
        changed.input_json = "changed".into();
        assert!(
            db.plan_merge_summary_unit(&op.operation_id, op.run_epoch, changed)
                .await
                .is_err()
        );
        db.split_merge_summary_unit(
            &op.operation_id,
            op.run_epoch,
            "e0",
            planned("e0-l"),
            planned("e0-r"),
        )
        .await
        .unwrap();
        assert_eq!(
            db.merge_summary_units(&op.operation_id)
                .await
                .unwrap()
                .len(),
            3
        );
        db.pause_session_merge(op.operation_id.clone(), op.run_epoch, "restart".into())
            .await
            .unwrap();
        let next = db
            .transition_session_merge(
                &op.operation_id,
                Some(
                    db.session_merge(&op.operation_id)
                        .await
                        .unwrap()
                        .unwrap()
                        .run_epoch,
                ),
                None,
                false,
            )
            .await
            .unwrap();
        let result = "{\"schemaVersion\":2,\"items\":[]}".to_owned();
        let hash = format!("{:x}", Sha256::digest(result.as_bytes()));
        assert!(
            db.commit_merge_summary_unit(
                &op.operation_id,
                op.run_epoch,
                "e0-l",
                result.clone(),
                hash.clone(),
                "model".into()
            )
            .await
            .is_err()
        );
        assert!(
            db.commit_merge_summary_unit(
                &op.operation_id,
                next.run_epoch,
                "e0-l",
                result.clone(),
                "bad".into(),
                "model".into()
            )
            .await
            .is_err()
        );
        db.commit_merge_summary_unit(
            &op.operation_id,
            next.run_epoch,
            "e0-l",
            result.clone(),
            hash.clone(),
            "model".into(),
        )
        .await
        .unwrap();
        assert!(
            db.commit_merge_summary_unit(
                &op.operation_id,
                next.run_epoch,
                "e0-l",
                result,
                hash,
                "model".into()
            )
            .await
            .is_err()
        );
    }
}
