import { act, cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { FileRewindDialog } from './FileRewindDialog';
import { useSessionStore } from '@/store/sessionStore';
vi.mock('@/components/ui', () => ({ Dialog: ({ children }: { children: React.ReactNode }) => <div>{children}</div>, Button: ({ children, variant: _variant, ...props }: React.ButtonHTMLAttributes<HTMLButtonElement> & { variant?: string }) => <button {...props}>{children}</button> }));
const response = (value: unknown, status = 200) => new Response(JSON.stringify(value), { status });
const snapshots = { turn: [{ messageId: 'turn', trackedFiles: ['/repo/one', '/repo/two'], timestamp: 'now' }] };
const preview = { previewToken: 'token', expiresInSeconds: 300, files: [{ filePath: '/repo/one', currentBytes: 10, restoredBytes: 5 }] };
beforeEach(() => useSessionStore.setState({ sessionId: 'session' }));
afterEach(() => { cleanup(); vi.restoreAllMocks(); vi.unstubAllGlobals(); });
describe('FileRewindDialog', () => {
    it('requires explicit file selection, a real preview, and confirmation before any restoration', async () => {
        const fetcher = vi.fn().mockResolvedValueOnce(response(snapshots)).mockResolvedValueOnce(response(preview)).mockResolvedValueOnce(response({ success: true, restoredFiles: ['/repo/one'], skippedFiles: [], errors: [] }));
        vi.stubGlobal('fetch', fetcher);
        const confirm = vi.spyOn(window, 'confirm').mockReturnValue(false);
        render(<FileRewindDialog sessionId="session" onClose={() => {}} />);
        await screen.findByRole('checkbox', { name: '/repo/one' });
        expect(screen.getByRole('button', { name: '预览所选文件' })).toBeDisabled();
        fireEvent.click(screen.getByRole('checkbox', { name: '/repo/one' }));
        fireEvent.click(screen.getByRole('button', { name: '预览所选文件' }));
        fireEvent.click(await screen.findByRole('button', { name: '确认回退' }));
        expect(fetcher).toHaveBeenCalledTimes(2);
        expect(JSON.parse(fetcher.mock.calls[1][1].body)).toEqual({ messageId: 'turn', filePaths: ['/repo/one'] });
        confirm.mockReturnValue(true);
        fireEvent.click(screen.getByRole('button', { name: '确认回退' }));
        expect(await screen.findByRole('status')).toHaveTextContent('文件回退完成：已恢复 1 个文件');
        expect(fetcher.mock.calls[2]).toEqual(['/api/sessions/session/history/rewind', expect.objectContaining({ method: 'POST', headers: { 'Content-Type': 'application/json', 'X-Session-Id': 'session' }, body: JSON.stringify({ previewToken: 'token', confirmed: true }) })]);
        expect(screen.queryByRole('button', { name: '确认回退' })).not.toBeInTheDocument();
    });
    it('shows partial failures without claiming that no files changed or automatically retrying', async () => {
        const fetcher = vi.fn().mockResolvedValueOnce(response(snapshots)).mockResolvedValueOnce(response(preview)).mockResolvedValueOnce(response({ success: false, restoredFiles: ['/repo/one'], skippedFiles: ['/repo/three'], errors: ['/repo/two: REWIND_WRITE_EFFECT_UNCERTAIN'] }));
        vi.stubGlobal('fetch', fetcher); vi.spyOn(window, 'confirm').mockReturnValue(true);
        render(<FileRewindDialog sessionId="session" onClose={() => {}} />);
        fireEvent.click(await screen.findByRole('checkbox', { name: '/repo/one' }));
        fireEvent.click(screen.getByRole('button', { name: '预览所选文件' }));
        fireEvent.click(await screen.findByRole('button', { name: '确认回退' }));
        expect(await screen.findByRole('alert')).toHaveTextContent('未全部完成：已恢复 1 个文件');
        expect(screen.getByRole('alert')).toHaveTextContent('REWIND_WRITE_EFFECT_UNCERTAIN');
        expect(screen.getByRole('alert')).toHaveTextContent('未处理：/repo/three');
        expect(fetcher).toHaveBeenCalledTimes(3);
    });
    it('invalidates a preview when selection changes and aborts a late read on session switch', async () => {
        let resolve!: (value: Response) => void;
        const fetcher = vi.fn().mockResolvedValueOnce(response(snapshots)).mockResolvedValueOnce(response(preview)).mockImplementationOnce(() => new Promise<Response>(done => { resolve = done; }));
        vi.stubGlobal('fetch', fetcher);
        const close = vi.fn();
        render(<FileRewindDialog sessionId="session" onClose={close} />);
        fireEvent.click(await screen.findByRole('checkbox', { name: '/repo/one' }));
        fireEvent.click(screen.getByRole('button', { name: '预览所选文件' }));
        await screen.findByRole('button', { name: '确认回退' });
        fireEvent.click(screen.getByRole('checkbox', { name: '/repo/two' }));
        expect(screen.queryByRole('button', { name: '确认回退' })).not.toBeInTheDocument();
        fireEvent.click(screen.getByRole('button', { name: '预览所选文件' }));
        act(() => useSessionStore.setState({ sessionId: 'next' }));
        await act(async () => { resolve(response(preview)); });
        await waitFor(() => expect(close).toHaveBeenCalledOnce());
        expect(fetcher.mock.calls[2][1].signal.aborted).toBe(true);
        expect(screen.queryByRole('button', { name: '确认回退' })).not.toBeInTheDocument();
    });
});
